channels:
- conda-forge
- bioconda
- nodefaults
dependencies:
- jupyterlab >=4.3.4,<5
- msprime >=1.3.3,<2
- tskit >=0.6.0,<0.7
- vcftools >=0.1.16,<0.2
- matplotlib >=3.10.0,<4
- seaborn >=0.13.2,<0.14
- demesdraw >=0.4.0,<0.5
- snakemake >=8.27.1,<9
